// คำศัพท์หมวดเสื้อผ้า
const WORDS_CLOTHES = [
  { emoji: "👕", th: "เสื้อยืด", en: "T-Shirt", category: "clothes", image: null },
  { emoji: "👔", th: "เสื้อเชิ้ต / เนคไท", en: "Shirt and Tie", category: "clothes", image: null },
  { emoji: "👚", th: "เสื้อสตรี", en: "Blouse", category: "clothes", image: null },
  { emoji: "🧥", th: "เสื้อโค้ท / เสื้อกันหนาว", en: "Coat", category: "clothes", image: null },
  { emoji: "🧥", th: "เสื้อแจ็คเก็ต", en: "Jacket", category: "clothes", image: null },
  { emoji: "🥼", th: "เสื้อกาวน์ / เสื้อแล็บ", en: "Lab Coat", category: "clothes", image: null },
  { emoji: "🦺", th: "เสื้อกั๊กนิรภัย", en: "Safety Vest", category: "clothes", image: null },
  { emoji: "👗", th: "ชุดเดรส / ชุดกระโปรง", en: "Dress", category: "clothes", image: null },
  { emoji: "🥻", th: "ชุดส่าหรี", en: "Sari", category: "clothes", image: null },
  { emoji: "🩱", th: "ชุดว่ายน้ำวันพีซ", en: "One-Piece Swimsuit", category: "clothes", image: null },
  { emoji: "🩲", th: "กางเกงใน / กางเก飲食", en: "Underpants", category: "clothes", image: null },
  { emoji: "🩳", th: "กางเกงขาสั้น", en: "Shorts", category: "clothes", image: null },
  { emoji: "👖", th: "กางเกงยีนส์ / กางเกงขายาว", en: "Jeans", category: "clothes", image: null },
  { emoji: "🧦", th: "ถุงเท้า", en: "Socks", category: "clothes", image: null },
  { emoji: "🧤", th: "ถุงมือ", en: "Gloves", category: "clothes", image: null },
  { emoji: "🧣", th: "ผ้าพันคอ", en: "Scarf", category: "clothes", image: null },
  { emoji: "🎩", th: "หมวกทรงสูง", en: "Top Hat", category: "clothes", image: null },
  { emoji: "🧢", th: "หมวกแก๊ป", en: "Cap", category: "clothes", image: null },
  { emoji: "👒", th: "หมวกปีกกว้าง", en: "Straw Hat", category: "clothes", image: null },
  { emoji: "👑", th: "มงกุฎ", en: "Crown", category: "clothes", image: null },
  { emoji: "🎒", th: "กระเป๋าเป้", en: "Backpack", category: "clothes", image: null },
  { emoji: "👝", th: "กระเป๋าคลัทช์ / กระเป๋าถือขนาดเล็ก", en: "Clutch Bag", category: "clothes", image: null },
  { emoji: "🛍️", th: "ถุงช้อปปิ้ง", en: "Shopping Bags", category: "clothes", image: null },
  { emoji: "👟", th: "รองเท้าผ้าใบ", en: "Sneakers", category: "clothes", image: null },
  { emoji: "👞", th: "รองเท้าหนัง / รองเท้าคัทชูชาย", en: "Man's Shoe", category: "clothes", image: null },
  { emoji: "🥿", th: "รองเท้าส้นแบน / รองเท้าคัทชูหญิง", en: "Flat Shoe", category: "clothes", image: null },
  { emoji: "👠", th: "รองเท้าส้นสูง", en: "High-Heeled Shoe", category: "clothes", image: null },
  { emoji: "👡", th: "รองเท้ารัดส้น / รองเท้าแตะผู้หญิง", en: "Woman's Sandal", category: "clothes", image: null },
  { emoji: "🥾", th: "รองเท้าบูทเดินป่า", en: "Hiking Boot", category: "clothes", image: null },
  { emoji: "👓", th: "แว่นตา", en: "Glasses", category: "clothes", image: null },
  { emoji: "🕶️", th: "แว่นกันแดด", en: "Sunglasses", category: "clothes", image: null }
];