// คำศัพท์หมวดสถานที่
const WORDS_PLACES = [
  { emoji: "🏠", th: "บ้าน", en: "House", category: "places", image: null },
  { emoji: "🏫", th: "โรงเรียน", en: "School", category: "places", image: null },
  { emoji: "🏥", th: "โรงพยาบาล", en: "Hospital", category: "places", image: null },
  { emoji: "🏪", th: "ร้านสะดวกซื้อ", en: "Convenience Store", category: "places", image: null },
  { emoji: "🏬", th: "ห้างสรรพสินค้า", en: "Department Store", category: "places", image: null },
  { emoji: "🏞️", th: "สวนสาธารณะ", en: "Park", category: "places", image: null },
  { emoji: "🏖️", th: "ชายหาด", en: "Beach", category: "places", image: null },
  { emoji: "🎡", th: "สวนสนุก", en: "Amusement Park", category: "places", image: null },
  { emoji: "🦁", th: "สวนสัตว์", en: "Zoo", category: "places", image: null },
  { emoji: "🏛️", th: "พิพิธภัณฑ์", en: "Museum", category: "places", image: null },
  { emoji: "⛪", th: "วัด", en: "Temple", category: "places", image: null },
  { emoji: "🚉", th: "สถานีรถไฟ", en: "Train Station", category: "places", image: null },
  { emoji: "🏦", th: "ธนาคาร", en: "Bank", category: "places", image: null },
  { emoji: "🍽️", th: "ร้านอาหาร", en: "Restaurant", category: "places", image: null },
  { emoji: "🏊", th: "สระว่ายน้ำ", en: "Swimming Pool", category: "places", image: null },
  { emoji: "🛒", th: "ตลาด", en: "Market", category: "places", image: null },
  { emoji: "☕", th: "ร้านกาแฟ", en: "Café", category: "places", image: null },
  { emoji: "🏢", th: "บริษัท / อาคารสำนักงาน", en: "Office building", category: "places", image: null },
  { emoji: "🏤", th: "ไปรษณีย์", en: "Post office", category: "places", image: null },
  { emoji: "👮", th: "สถานีตำรวจ", en: "Police station", category: "places", image: null },
  { emoji: "🚒", th: "สถานีดับเพลิง", en: "Fire station", category: "places", image: null },
  { emoji: "🏟️", th: "สนามกีฬา", en: "Stadium", category: "places", image: null },
  { emoji: "🎬", th: "โรงภาพยนตร์", en: "Movie theater", category: "places", image: null },
  { emoji: "⛰️", th: "ภูเขา", en: "Mountain", category: "places", image: null },
  { emoji: "🛫", th: "สนามบิน", en: "Airport", category: "places", image: null }
]