// คำศัพท์หมวดโรงเรียน
const WORDS_SCHOOL = [
  { emoji: "🎒", th: "กระเป๋านักเรียน", en: "School Bag", category: "school", image: null },
  { emoji: "✏️", th: "ดินสอ", en: "Pencil", category: "school", image: null },
  { emoji: "✒️", th: "ปากกาหมึกซึม", en: "Pen", category: "school", image: null },
  { emoji: "🖊️", th: "ปากกาลูกลื่น", en: "Ballpoint Pen", category: "school", image: null },
  { emoji: "🖍️", th: "สีเทียน / สีชอล์ก", en: "Crayon", category: "school", image: null },
  { emoji: "🖌️", th: "พู่กัน", en: "Paintbrush", category: "school", image: null },
  { emoji: "📏", th: "ไม้บรรทัด", en: "Ruler", category: "school", image: null },
  { emoji: "📐", th: "ไม้ฉากสามเหลี่ยม", en: "Triangular Ruler", category: "school", image: null },
  { emoji: "✂️", th: "กรรไกร", en: "Scissors", category: "school", image: null },
  { emoji: "📌", th: "หมุดปักกระดาษ", en: "Pushpin", category: "school", image: null },
  { emoji: "📎", th: "คลิปหนีบกระดาษ", en: "Paperclip", category: "school", image: null },
  { emoji: "📕", th: "หนังสือ", en: "Book", category: "school", image: null },
  { emoji: "📓", th: "สมุดบันทึก", en: "Notebook", category: "school", image: null },
  { emoji: "📝", th: "สมุดจด / บันทึกย่อ", en: "Memo", category: "school", image: null },
  { emoji: "📁", th: "แฟ้มเอกสาร", en: "Folder", category: "school", image: null },
  { emoji: "📊", th: "แผนภูมิ / กราฟ", en: "Chart", category: "school", image: null },
  { emoji: "🎨", th: "จานสี (วิชาศิลปะ)", en: "Palette (Art)", category: "school", image: null },
  { emoji: "🔬", th: "กล้องจุลทรรศน์ (วิชาวิทยาศาสตร์)", en: "Microscope (Science)", category: "school", image: null },
  { emoji: "🔭", th: "กล้องโทรทรรศน์ / กล้องดูดาว", en: "Telescope", category: "school", image: null },
  { emoji: "🧪", th: "หลอดทดลอง", en: "Test Tube", category: "school", image: null },
  { emoji: "🧮", th: "ลูกคิด (วิชาคณิตศาสตร์)", en: "Abacus (Math)", category: "school", image: null },
  { emoji: "🗺️", th: "แผนที่ (วิชาภูมิศาสตร์)", en: "Map (Geography)", category: "school", image: null },
  { emoji: "🌐", th: "ลูกโลก", en: "Globe", category: "school", image: null },
  { emoji: "🏫", th: "โรงเรียน", en: "School Building", category: "school", image: null },
  { emoji: "🏫", th: "ห้องเรียน", en: "Classroom", category: "school", image: null }, // สามารถใช้ซ้ำหรือสื่อบริบทได้
  { emoji: "🧑‍🏫", th: "คุณครู", en: "Teacher", category: "school", image: null },
  { emoji: "🧑‍🎓", th: "นักเรียน / นักศึกษา", en: "Student", category: "school", image: null },
  { emoji: "🔔", th: "ระฆัง / ออดโรงเรียน", en: "School Bell", category: "school", image: null },
  { emoji: "🚌", th: "รถโรงเรียน", en: "School Bus", category: "school", image: null },
  { emoji: "🏆", th: "ถ้วยรางวัล", en: "Trophy", category: "school", image: null },
  { emoji: "🥇", th: "เหรียญทอง", en: "Gold Medal", category: "school", image: null }
];