// คำศัพท์หมวดสัตว์
// รูปภาพ: Wikimedia Commons (public domain / CC) ลิงก์ตรง ไม่ต้องเก็บไฟล์ในโปรเจกต์
const WORDS_ANIMALS = [
  // { emoji: "🐶", th: "หมา", en: "Dog", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Dog_%28Canis_lupus_familiaris%29_%281%29.jpg" },
  // { emoji: "🐱", th: "แมว", en: "Cat", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/7/74/A-Cat.jpg" },
  // { emoji: "🐘", th: "ช้าง", en: "Elephant", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Elephant.jpg" },
  // { emoji: "🦁", th: "สิงโต", en: "Lion", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Lion_%28close-up_face%29.jpg" },
  // { emoji: "🐰", th: "กระต่าย", en: "Rabbit", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/1/12/Rabbit_side_view.JPG" },
  // { emoji: "🐟", th: "ปลา", en: "Fish", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Clownfish.jpg" },
  // { emoji: "🐔", th: "ไก่", en: "Chicken", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Chicken_01.JPG" },
  // { emoji: "🐸", th: "กบ", en: "Frog", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Frog_on_a_leaf.jpg" },
  // { emoji: "🐷", th: "หมู", en: "Pig", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Happy_pig.jpg/500px-Happy_pig.jpg" },
  // { emoji: "🐦", th: "นก", en: "Bird", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/3/36/Sparrow.jpg" },
  // { emoji: "🐯", th: "เสือ", en: "Tiger", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/4/43/A_young_Tigress.jpg" },
  // { emoji: "🐵", th: "ลิง", en: "Monkey", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Rhesus_macaque_monkey_1.jpg" },
  // { emoji: "🐻", th: "หมี", en: "Bear", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Brown_bear_1101.jpg" },
  // { emoji: "🦓", th: "ม้าลาย", en: "Zebra", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Plains_Zebra_%28Equus_quagga%29_stallion.jpg" },
  // { emoji: "🦒", th: "ยีราฟ", en: "Giraffe", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/9/90/Giraffe_in_Tarangire_National_Park.jpg" },
  // { emoji: "🐴", th: "ม้า", en: "Horse", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/A_black_horse_in_the_field.jpg" },
  // { emoji: "🐑", th: "แกะ", en: "Sheep", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Domestic_sheep.jpg" },
  // { emoji: "🦆", th: "เป็ด", en: "Duck", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Mallard_Hatfield_Forest_Lake_01.jpg" },
  // { emoji: "🦉", th: "นกฮูก", en: "Owl", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Asio_otus_01_ms.jpg" },
  // { emoji: "🐧", th: "เพนกวิน", en: "Penguin", category: "animals", image: "https://upload.wikimedia.org/wikipedia/commons/d/da/Penguin_at_the_Colchester_Zoo.jpg" },
  { emoji: "🐶", th: "หมา", en: "Dog", category: "animals", image: null },
  { emoji: "🐱", th: "แมว", en: "Cat", category: "animals", image: null },
  { emoji: "🐘", th: "ช้าง", en: "Elephant", category: "animals", image: null },
  { emoji: "🦁", th: "สิงโต", en: "Lion", category: "animals", image: null },
  { emoji: "🐰", th: "กระต่าย", en: "Rabbit", category: "animals", image: null },
  { emoji: "🐟", th: "ปลา", en: "Fish", category: "animals", image: null },
  { emoji: "🐔", th: "ไก่", en: "Chicken", category: "animals", image: null },
  { emoji: "🐸", th: "กบ", en: "Frog", category: "animals", image: null },
  { emoji: "🐷", th: "หมู", en: "Pig", category: "animals", image: null },
  { emoji: "🐦", th: "นก", en: "Bird", category: "animals", image: null },
  { emoji: "🐯", th: "เสือ", en: "Tiger", category: "animals", image: null },
  { emoji: "🐵", th: "ลิง", en: "Monkey", category: "animals", image: null },
  { emoji: "🐻", th: "หมี", en: "Bear", category: "animals", image: null },
  { emoji: "🦓", th: "ม้าลาย", en: "Zebra", category: "animals", image: null },
  { emoji: "🦒", th: "ยีราฟ", en: "Giraffe", category: "animals", image: null },
  { emoji: "🐴", th: "ม้า", en: "Horse", category: "animals", image: null },
  { emoji: "🐑", th: "แกะ", en: "Sheep", category: "animals", image: null },
  { emoji: "🦆", th: "เป็ด", en: "Duck", category: "animals", image: null },
  { emoji: "🦉", th: "นกฮูก", en: "Owl", category: "animals", image: null },
  { emoji: "🐧", th: "เพนกวิน", en: "Penguin", category: "animals", image: null },
];
