// คำศัพท์หมวดสัตว์
// รูปภาพ: Wikimedia Commons (public domain / CC) ลิงก์ตรง ไม่ต้องเก็บไฟล์ในโปรเจกต์
const WORDS_ANIMALS = [
  // 1-20 (ข้อมูลเดิมของคุณ)
  { emoji: "🐶", th: "หมา", en: "Dog", category: "animals", image: null },
  { emoji: "🐱", th: "แมว", en: "Cat", category: "animals", image: null },
  { emoji: "🐘", th: "ช้าง", en: "Elephant", category: "animals", image: null },
  { emoji: "🦁", th: "สิงโต", en: "Lion", category: "animals", image: null },
  { emoji: "🐰", th: "กระต่าย", en: "Rabbit", category: "animals", image: null },
  { emoji: "🐟", th: "ปลา", en: "Fish", category: "animals", image: null },
  { emoji: "🐔", th: "ไก่", en: "Chicken", category: "animals", image: null },
  { emoji: "🐸", th: "กบ", en: "Frog", category: "animals", image: null },
  { emoji: "🐷", th: "หมู", en: "Pig", category: "animals", image: null },
  { emoji: "🐦", th: "นก", en: "Bird", category: "animals", image: null },
  { emoji: "🐯", th: "เสือ", en: "Tiger", category: "animals", image: null },
  { emoji: "🐵", th: "ลิง", en: "Monkey", category: "animals", image: null },
  { emoji: "🐻", th: "หมี", en: "Bear", category: "animals", image: null },
  { emoji: "🦓", th: "ม้าลาย", en: "Zebra", category: "animals", image: null },
  { emoji: "🦒", th: "ยีราฟ", en: "Giraffe", category: "animals", image: null },
  { emoji: "🐴", th: "ม้า", en: "Horse", category: "animals", image: null },
  { emoji: "🐑", th: "แกะ", en: "Sheep", category: "animals", image: null },
  { emoji: "🦆", th: "เป็ด", en: "Duck", category: "animals", image: null },
  { emoji: "🦉", th: "นกฮูก", en: "Owl", category: "animals", image: null },
  { emoji: "🐧", th: "เพนกวิน", en: "Penguin", category: "animals", image: null },

  // 21-40
  { emoji: "🦊", th: "สุนัขจิ้งจอก", en: "Fox", category: "animals", image: null },
  { emoji: "🐺", th: "หมาป่า", en: "Wolf", category: "animals", image: null },
  { emoji: "🐗", th: "หมูป่า", en: "Wild Boar", category: "animals", image: null },
  { emoji: "🐹", th: "แฮมสเตอร์", en: "Hamster", category: "animals", image: null },
  { emoji: "🐭", th: "หนู", en: "Mouse", category: "animals", image: null },
  { emoji: "🐮", th: "วัว", en: "Cow", category: "animals", image: null },
  { emoji: "🐐", th: "แพะ", en: "Goat", category: "animals", image: null },
  { emoji: "🐪", th: "อูฐ", en: "Camel", category: "animals", image: null },
  { emoji: "🦙", th: "ลามะ", en: "Llama", category: "animals", image: null },
  { emoji: "🦘", th: "จิงโจ้", en: "Kangaroo", category: "animals", image: null },
  { emoji: "🦡", th: "แบดเจอร์", en: "Badger", category: "animals", image: null },
  { emoji: "🦃", th: "ไก่งวง", en: "Turkey", category: "animals", image: null },
  { emoji: "🦅", th: "นกอินทรี", en: "Eagle", category: "animals", image: null },
  { emoji: "🦚", th: "นกยูง", en: "Peacock", category: "animals", image: null },
  { emoji: "🦢", th: "หงส์", en: "Swan", category: "animals", image: null },
  { emoji: "🦩", th: "นกฟลามิงโก", en: "Flamingo", category: "animals", image: null },
  { emoji: "🕊️", th: "นกพิราบ", en: "Dove", category: "animals", image: null },
  { emoji: "🦇", th: "ค้างคาว", en: "Bat", category: "animals", image: null },
  { emoji: "🦈", th: "ฉลาม", en: "Shark", category: "animals", image: null },
  { emoji: "🐬", th: "โลมา", en: "Dolphin", category: "animals", image: null },

  // 41-60
  { emoji: "🐋", th: "วาฬ", en: "Whale", category: "animals", image: null },
  { emoji: "🐙", th: "ปลาหมึกยักษ์", en: "Octopus", category: "animals", image: null },
  { emoji: "🦀", th: "ปู", en: "Crab", category: "animals", image: null },
  { emoji: "🦞", th: "กุ้งมังกร", en: "Lobster", category: "animals", image: null },
  { emoji: "🦐", th: "กุ้ง", en: "Shrimp", category: "animals", image: null },
  { emoji: "🐢", th: "เต่า", en: "Turtle", category: "animals", image: null },
  { emoji: "🐊", th: "จระเข้", en: "Crocodile", category: "animals", image: null },
  { emoji: "🐍", th: "งู", en: "Snake", category: "animals", image: null },
  { emoji: "🦎", th: "กิ้งก่า", en: "Lizard", category: "animals", image: null },
  { emoji: "🐆", th: "เสือดาว", en: "Leopard", category: "animals", image: null },
  { emoji: "🦏", th: "แรด", en: "Rhinoceros", category: "animals", image: null },
  { emoji: "🦛", th: "ฮิปโปโปเตมัส", en: "Hippopotamus", category: "animals", image: null },
  { emoji: "🦦", th: "นาก", en: "Otter", category: "animals", image: null },
  { emoji: "🦫", th: "บีเวอร์", en: "Beaver", category: "animals", image: null },
  { emoji: "🐿️", th: "กระรอก", en: "Squirrel", category: "animals", image: null },
  { emoji: "🦔", th: "เม่น", en: "Hedgehog", category: "animals", image: null },
  { emoji: "🦥", th: "สล็อท", en: "Sloth", category: "animals", image: null },
  { emoji: "🐨", th: "โคอาลา", en: "Koala", category: "animals", image: null },
  { emoji: "🐼", th: "แพนด้า", en: "Panda", category: "animals", image: null },
  { emoji: "🦌", th: "กวาง", en: "Deer", category: "animals", image: null },

  // 61-80
  { emoji: "🦄", th: "ยูนิคอร์น", en: "Unicorn", category: "animals", image: null },
  { emoji: "🐝", th: "ผึ้ง", en: "Bee", category: "animals", image: null },
  { emoji: "🐛", th: "หนอน", en: "Caterpillar", category: "animals", image: null },
  { emoji: "🦋", th: "ผีเสื้อ", en: "Butterfly", category: "animals", image: null },
  { emoji: "🐌", th: "หอยทาก", en: "Snail", category: "animals", image: null },
  { emoji: "🐞", th: "เต่าทอง", en: "Ladybug", category: "animals", image: null },
  { emoji: "🐜", th: "มด", en: "Ant", category: "animals", image: null },
  { emoji: "🕷️", th: "แมงมุม", en: "Spider", category: "animals", image: null },
  { emoji: "🦂", th: "แมงป่อง", en: "Scorpion", category: "animals", image: null },
  { emoji: "🦟", th: "ยุง", en: "Mosquito", category: "animals", image: null },
  { emoji: "🦗", th: "ตั๊กแตน", en: "Grasshopper", category: "animals", image: null },
  { emoji: "🦎", th: "ตุ๊กแก", en: "Gecko", category: "animals", image: null },
  { emoji: "🐠", th: "ปลาการ์ตูน", en: "Tropical Fish", category: "animals", image: null },
  { emoji: "🐡", th: "ปลาปักเป้า", en: "Pufferfish", category: "animals", image: null },
  { emoji: "🦑", th: "ปลาหมึกกล้วย", en: "Squid", category: "animals", image: null },
  { emoji: "🦪", th: "หอยนางรม", en: "Oyster", category: "animals", image: null },
  // { emoji: " jellyfish" /* 🪼 */, th: "แมงกะพรุน", en: "Jellyfish", category: "animals", image: null },
  { emoji: "🦭", th: "แมวน้ำ", en: "Seal", category: "animals", image: null },
  // { emoji: " walrus" /* 🦣 */, th: "แมมมอธ", en: "Mammoth", category: "animals", image: null },
  { emoji: "🐕‍🦺", th: "สุนัขช่วยเหลือ", en: "Service Dog", category: "animals", image: null },

  // 81-100
  { emoji: "🐩", th: "สุนัขพุดเดิ้ล", en: "Poodle", category: "animals", image: null },
  { emoji: "🐈", th: "แมวบ้าน", en: "Domestic Cat", category: "animals", image: null },
  { emoji: "🐂", th: "วัวตัวผู้", en: "Ox", category: "animals", image: null },
  { emoji: "🐃", th: "ควาย", en: "Water Buffalo", category: "animals", image: null },
  { emoji: "🐄", th: "แม่วัว", en: "Dairy Cow", category: "animals", image: null },
  { emoji: "🐖", th: "แม่หมู", en: "Sow", category: "animals", image: null },
  { emoji: "🐏", th: "แกะตัวผู้", en: "Ram", category: "animals", image: null },
  { emoji: "🐃", th: "กระทิง", en: "Bull", category: "animals", image: null },
  { emoji: "🐓", th: "พ่อไก่", en: "Rooster", category: "animals", image: null },
  { emoji: "🐣", th: "ลูกไก่เพิ่งฟัก", en: "Hatching Chick", category: "animals", image: null },
  { emoji: "🐤", th: "ลูกไก่", en: "Baby Chick", category: "animals", image: null },
  { emoji: "🐦", th: "นกน้อย", en: "Small Bird", category: "animals", image: null },
  { emoji: "🦅", th: "นกเหยี่ยว", en: "Hawk", category: "animals", image: null },
  { emoji: "🦜", th: "นกแก้ว", en: "Parrot", category: "animals", image: null },
  { emoji: "🦤", th: "นกดอนโด", en: "Dodo", category: "animals", image: null },
  { emoji: "🦡", th: "ฮันนี่แบดเจอร์", en: "Honey Badger", category: "animals", image: null },
  { emoji: "🦫", th: "นากทะเล", en: "Sea Otter", category: "animals", image: null },
  { emoji: "🦧", th: "ลิงอุรังอุตัง", en: "Orangutan", category: "animals", image: null },
  { emoji: "🦍", th: "ลิงกอริลลา", en: "Gorilla", category: "animals", image: null },
  { emoji: "🐕", th: "สุนัข", en: "Hound", category: "animals", image: null }
];
