// คำศัพท์หมวดผลไม้
// รูปภาพ: Wikimedia Commons (public domain / CC) ลิงก์ตรง ไม่ต้องเก็บไฟล์ในโปรเจกต์
const WORDS_FRUITS = [
  { emoji: "🍎", th: "แอปเปิ้ลแดง", en: "Red Apple", category: "fruits", image: null },
  { emoji: "🍏", th: "แอปเปิ้ลเขียว", en: "Green Apple", category: "fruits", image: null },
  { emoji: "🍐", th: "ลูกแพร์", en: "Pear", category: "fruits", image: null },
  { emoji: "🍊", th: "ส้ม", en: "Orange", category: "fruits", image: null },
  { emoji: "🍋", th: "เลมอน", en: "Lemon", category: "fruits", image: null },
  { emoji: "🍌", th: "กล้วย", en: "Banana", category: "fruits", image: null },
  { emoji: "🍉", th: "แตงโม", en: "Watermelon", category: "fruits", image: null },
  { emoji: "🍇", th: "องุ่น", en: "Grape", category: "fruits", image: null },
  { emoji: "🍓", th: "สตรอว์เบอร์รี่", en: "Strawberry", category: "fruits", image: null },
  { emoji: "🫐", th: "บลูเบอร์รี่", en: "Blueberry", category: "fruits", image: null },
  { emoji: "🍈", th: "เมลอน", en: "Melon", category: "fruits", image: null },
  { emoji: "🍒", th: "เชอร์รี่", en: "Cherry", category: "fruits", image: null },
  { emoji: "🍑", th: "ลูกพีช", en: "Peach", category: "fruits", image: null },
  { emoji: "🥭", th: "มะม่วง", en: "Mango", category: "fruits", image: null },
  { emoji: "🍍", th: "สับปะรด", en: "Pineapple", category: "fruits", image: null },
  { emoji: "🥥", th: "มะพร้าว", en: "Coconut", category: "fruits", image: null },
  { emoji: "🥝", th: "กีวี่", en: "Kiwi", category: "fruits", image: null },
  { emoji: "🍅", th: "มะเขือเทศ", en: "Tomato", category: "fruits", image: null },
  { emoji: "🥑", th: "อะโวคาโด", en: "Avocado", category: "fruits", image: null },
  { emoji: "🫒", th: "มะกอก", en: "Olive", category: "fruits", image: null },
  { emoji: "🫚", th: "ขิง", en: "Ginger", category: "fruits", image: null },
  { emoji: "🥜", th: "ถั่วลิสง", en: "Peanut", category: "fruits", image: null },
  { emoji: "🌰", th: "เกาลัด", en: "Chestnut", category: "fruits", image: null },
  { emoji: "🫘", th: "เมล็ดถั่ว", en: "Beans", category: "fruits", image: null },
  { emoji: "🌶️", th: "พริก", en: "Chili Pepper", category: "fruits", image: null },
  { emoji: "🫑", th: "พริกหวาน", en: "Bell Pepper", category: "fruits", image: null },
  { emoji: "🌽", th: "ข้าวโพด", en: "Corn", category: "fruits", image: null },
  { emoji: "🥕", th: "แครอท", en: "Carrot", category: "fruits", image: null },
  { emoji: "🥔", th: "มันฝรั่ง", en: "Potato", category: "fruits", image: null },
  { emoji: "🍠", th: "มันเผา", en: "Roasted Sweet Potato", category: "fruits", image: null },
  { emoji: "🍆", th: "มะเขือยาว", en: "Eggplant", category: "fruits", image: null }
];
